### ISSUE TITLE
Problem with timeouts on windows

### ISSUE THREAD

**Issue by MLerik** [AIcrowd/flatland-challenge-starter-kit#1]
This error message occurs when running locally on windos:
```
Listening at :  flatland-rl::FLATLAND_RL_SERVICE_ID::commands
Traceback (most recent call last):
  File "c:\users\u224870\appdata\local\continuum\anaconda3\envs\flatland-rl\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\u224870\appdata\local\continuum\anaconda3\envs\flatland-rl\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\u224870\AppData\Local\Continuum\anaconda3\envs\flatland-rl\Scripts\flatland-evaluator.exe\__main__.py", line 9, in <module>
  File "c:\users\u224870\appdata\local\continuum\anaconda3\envs\flatland-rl\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\u224870\appdata\local\continuum\anaconda3\envs\flatland-rl\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\u224870\appdata\local\continuum\anaconda3\envs\flatland-rl\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\u224870\appdata\local\continuum\anaconda3\envs\flatland-rl\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\u224870\appdata\local\continuum\anaconda3\envs\flatland-rl\lib\site-packages\flatland\cli.py", line 81, in evaluator
    grader.run()
  File "c:\users\u224870\appdata\local\continuum\anaconda3\envs\flatland-rl\lib\site-packages\flatland\evaluators\service.py", line 528, in run
    command = self.get_next_command()
  File "c:\users\u224870\appdata\local\continuum\anaconda3\envs\flatland-rl\lib\site-packages\flatland\evaluators\service.py", line 221, in get_next_command
    command = self._get_next_command(_redis)
  File "c:\users\u224870\appdata\local\continuum\anaconda3\envs\flatland-rl\lib\site-packages\timeout_decorator\timeout_decorator.py", line 78, in new_function
    old = signal.signal(signal.SIGALRM, handler)
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

**Comment by spMohanty** [comment]
The problem is because we use `timeout_decorator` internally to manage timeouts of different internal calls. Looks like the best solution is simply to use a no-op for timeout in case of Windows, as the timeouts are anyway essential only on the evaluator.
